### ISSUE TITLE
Various PHP 8 & PHP 8.2 issues

### ISSUE THREAD

**Issue by ElusiveMind** [backdrop-contrib/h5p#6]
In PHP 8, curly brackets can not be used for array references.
Last Update for metadata from H5P was throwing errors on DateTime when it had never been run or "false" (not 0, the string false).
Dynamic class properties are deprecated as of PHP 8.2

**Comment by docwilmot** [comment]
Thanks I've merged the PR. Please let me know if you think there'll be other issues before I re-release.

**Comment by argiepiano** [comment]
I've encountered this again after downloading the current release (which is outdated). Can we please have a new release?

**Comment by ElusiveMind** [comment]
Thank you for the heads up. Can you tell me which issues you are having? It will point me in the right direction of a fix

**Comment by argiepiano** [comment]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /Users/XXX/Sites/localhost/XXX/modules/h5p/library/h5p.classes.php on line 2809

This is with the current release. I haven't tried the dev version.

**Comment by docwilmot** [comment]
Made a new release with latest commits, sorry for the delay.
